name: SimpleHealthBars
main: de.themoep.SimpleHealthBars.SimpleHealthBars
version: '${minecraft.plugin.version}'
api-version: 1.13
description: Lets you display healthbars for mobs
authors: [Phoenix616]
website: https://github.com/Minebench/SimpleHealthBars
commands:
   simplehealthbars:
      aliases: [shb]
      description: Adminstrative Command (reloading)
      usage: /<command>
      permission: simplehealthbar.command
      permission-message: You don't have the permission <permission>
permissions:
   simplehealthbars.command:
      description: Gives permission to the simplehealthbars command
      default: op