name: SimpleHealthBar
main: de.themoep.SimpleHealthBar.SimpleHealthBar
version: 0.1.2
description: Lets you display healthbars for mobs
authors: [Phoenix616]
commands:
   simplehealthbar:
      aliases: [shb]
      description: Adminstrative Command (reloading)
      usage: /<command>
      permission: simplehealthbar.command
      permission-message: You don't have the permission <permission>
permissions:
   simplehealthbar.command:
      description: Gives permission to the simplehealthbar command
      default: op